# Generated by Django 4.0.5 on 2022-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquote',
            name='creator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='collections',
            name='creator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
