# Generated by Django 4.0.5 on 2022-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_bookquote_creator_collections_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookquote',
            name='creator',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collections',
            name='creator',
            field=models.CharField(max_length=200),
        ),
    ]
