# Generated by Django 4.0.5 on 2022-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_alter_bookquote_creator_alter_collections_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquote',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookquote',
            name='year_of_publicatoin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
