# Generated by Django 4.0.5 on 2022-09-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_bookquote_page_bookquote_year_of_publicatoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookquote',
            old_name='year_of_publicatoin',
            new_name='year_of_publication',
        ),
    ]
